### ISSUE TITLE
UX/UI Design

### ISSUE THREAD

**Issue by Faithful1** [BuildForSDGCohort2/Confyde-Frontend#2]
## One Single Source of Truth for Confyde Application
FIGMA UI:  https://www.figma.com/file/GMhNrKQrbs37j9dsuaa2hI/Confyde-App?node-id=1%3A2

### Todo
- [x] Handover to Leo
- [x] Wireframing (Maybe Clickable)
- [ ] Style Guides
- [x] Prototyping/mockups
- [ ] Navigation
- [ ] Landing Page
- [ ] Footer
- [ ] Links
- [ ] Color Scheme
- [x] Login and Sign up

**Comment by jamesoyanna** [comment]
Design of Mock up for the App is currently in progress.

**Comment by Faithful1** [comment]
We are currently transferring the ui ux design tasks to @theLeoU  on Figma ASAP

**Comment by Faithful1** [comment]
@jamesoyanna  just following up on this have you handed over to Leo. Kindly do ASAP and update on here. Cheers

**Comment by Leoactionz** [comment]
https://www.figma.com/file/GMhNrKQrbs37j9dsuaa2hI/Confyde-App?node-id=0%3A1

Login and Signup page drafted, I will love your feedback and comment
